commerce_payment.commerce_payment_gateway.plugin.reddotpayment_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    redirect_method:
      type: string
      label: 'Redirect method'
